### ISSUE TITLE
Issue With Microsoft.Extensions.DependencyModel, Version=1.1.1

### ISSUE THREAD

**Issue by blueflash2o** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#14]
Updated to the latest AspNetCore.Mvc versions 1.1.2 with using the framework net452 I get the error at the bottom.

The setup in Startup.cs
```
public void ConfigureServices(IServiceCollection services)
{
   services.AddCors(options =>
   {
      options.AddPolicy("AllowSpecificOrigin",
         builder => builder.WithOrigins("http://localhost:16964"));
   });

   services.AddMvc();
   services.Configure<MvcOptions>(options =>
         {
            options.Filters.Add(new CorsAuthorizationFilterFactory("AllowSpecificOrigin"));
         });
   services.AddAutoMapper();

... other services
}
```
The error
```
System.IO.FileLoadException was unhandled
  FileName=Microsoft.Extensions.DependencyModel, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
  FusionLog=""
  HResult=-2146234304
  Message=Could not load file or assembly 'Microsoft.Extensions.DependencyModel, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  Source=AutoMapper.Extensions.Microsoft.DependencyInjection
  StackTrace:
       at AutoMapper.ServiceCollectionExtensions.AddAutoMapper(IServiceCollection services)
       at Api.Enterprise.Startup.ConfigureServices(IServiceCollection services) in "Project Path Removed Main project folder"\Startup.cs:line 99
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
       at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
       at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
       at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
       at Api.Enterprise.Program.Main(String[] args) in "Project Path Removed Main project folder"\Program.cs:line 18
  InnerException: 
       FileName=Microsoft.Extensions.DependencyModel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
       FusionLog==== Pre-bind state information ===
LOG: DisplayName = Microsoft.Extensions.DependencyModel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
 (Fully-specified)
LOG: Appbase = file:///"Project Path Removed Main project folder"/bin/Debug/net452/win7-x64/
LOG: Initial PrivatePath = NULL
Calling assembly : AutoMapper.Extensions.Microsoft.DependencyInjection, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: "Project Path Removed Main project folder"\bin\Debug\net452\win7-x64\Enterprise.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Redirect found in application configuration file: 1.0.0.0 redirected to 1.1.0.0.
LOG: Post-policy reference: Microsoft.Extensions.DependencyModel, Version=1.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
LOG: Attempting download of new URL file:///"Project Path Removed Main project folder"/bin/Debug/net452/win7-x64/Microsoft.Extensions.DependencyModel.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Build Number
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

       HResult=-2146234304
       Message=Could not load file or assembly 'Microsoft.Extensions.DependencyModel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
       InnerException: 

```

The references are happy
![image](https://cloud.githubusercontent.com/assets/11382880/23954688/fb939c40-0965-11e7-8118-8261f7283e76.png)

**Comment by RenanCarlosPereira** [comment]
Got the same issue.
Im using Visual studio 2017 asp.netCore 1.1

**Comment by jbogard** [comment]
Try the latest drop, 2.0.1

**Comment by AlexanderGurinov** [comment]
And I got a NullReferenceException in 2.0.1 with `serviceCollection.AddAutoMapper()`. Stack trace:

>    at AutoMapper.ServiceCollectionExtensions.GetCandidateLibraries(DependencyContext dependencyContext)
>    at AutoMapper.ServiceCollectionExtensions.GetCandidateAssemblies(DependencyContext dependencyContext)
>    at AutoMapper.ServiceCollectionExtensions.AddAutoMapper(IServiceCollection services, Action`1 additionalInitAction)

My DependencyContext.Default is null. And my project is using .NET Framework 4.6.1.

**Comment by jbogard** [comment]
@AlexanderGurinov if you're hitting that, then you can't use the overload that uses DependencyContext.Default. Pass in the assemblies/type markers explicitly.

**Comment by prochnowc** [comment]
@alexandergurinov if you enable PreserveCompilationContext you should have a deps.json file in output directory. This file is required for DependencyContext to work either in filesystem or embedded as a resource. If the issue is caused by unit tests you need to disable shadow copying.
