### ISSUE TITLE
.net core 2.0 xunit integration test

### ISSUE THREAD

**Issue by kk4fun** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#28]
Hi, i have an error after upgrade to .net core 2.0 from 1.1 when try run integration test with xunit framework, but when i comment `services.AddAutoMapper();` in the `ConfigureServices(IServiceCollection services)` from `Startup` class it works fine
```
 public class ThingsController_Tests
    {
        private readonly HttpClient _client;
        public ThingsController_Tests()
        {
            var hostBuilder = new WebHostBuilder();

            
            var server = new TestServer(hostBuilder.UseStartup<Startup>());
            this._client = server.CreateClient();
        }
...
```

packages from my test project, it has link to main project
```
<PackageReference Include="Microsoft.AspNetCore.TestHost" Version="2.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0" />
    <PackageReference Include="xunit.runner.console" Version="2.2.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
    <PackageReference Include="xunit" Version="2.2.0" />
    <PackageReference Include="xunit.runners" Version="2.0.0" />
```

automapper packages in main project 
 ```
 <PackageReference Include="automapper" Version="6.1.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="3.0.1" />
```
help pls :)
```
at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at AutoMapper.ServiceCollectionExtensions.AddAutoMapperClasses(IServiceCollection services, Action`1 additionalInitAction, IEnumerable`1 assembliesToScan)
   at myProjectName.Startup.ConfigureServices(IServiceCollection services) in myProjectPath
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Microsoft.AspNetCore.TestHost.TestServer..ctor(IWebHostBuilder builder, IFeatureCollection featureCollection)
   at Tests_myprojectName.ThingsController_Tests..ctor() in myProjectPath
Result Message:	System.Reflection.ReflectionTypeLoadException : Unable to load one or more of the requested types.
```

**Comment by lbargaoanu** [comment]
You need to find out exactly the types that are not loaded and why. That info is inside that exception object. Probably this has nothing to do with AM.

**Comment by kk4fun** [comment]
thx , i find workaround - when i add automapper in DI container like  `services.AddAutoMapper(typeof(Startup));` all working fine

**Comment by jbogard** [comment]
OK I think this is actually a bug, I've switched the assembly loading to use AppDomain for the default option.

**Comment by kk4fun** [comment]
thanks :)

**Comment by riiight** [comment]
It sounds like this is already being worked on but I also wanted to chime in and say that I am also experiencing issues with profiles not being loaded in a .NET Core 2.0 app after upgrading AM.E.M.DI from 2.0.1 to 3.0.1.

In my case, it appears as though profiles from a dependency class library are not being loaded, but strangely the the profiles of a dependency of that dependency are being loaded. Hope that helps.

**Comment by peterdeme** [comment]
We are also facing the same issue.
```
---- System.TypeInitializationException : The type initializer for 'IntegrationTests.Tests.TestServerFixture' threw an exception.
-------- System.Reflection.ReflectionTypeLoadException : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
---- The following constructor parameters did not have matching fixture data: IntegrationTestFixture testFixture

----- Inner Stack Trace #1 (System.TypeInitializationException) -----
   at IntegrationTests.Tests.IntegrationTestFixture..ctor() in C:\build.tc\agent\[...]\IntegrationTests\Tests\IntegrationTestFixture.cs:line 25
----- Inner Stack Trace -----
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at AutoMapper.ServiceCollectionExtensions.AddAutoMapperClasses(IServiceCollection services, Action`1 additionalInitAction, IEnumerable`1 assembliesToScan)
```

**Comment by jbogard** [comment]
I think the best thing to do is to explicitly tell AutoMapper which assemblies to load from.

**Comment by michael-freidgeim-webjet** [comment]
@jbogard , Can you catch the ReflectionTypeLoadException exception in AddAutoMapperClasses method and provide hint for the possible fix (e.g. link to this thread).
It will help developers to quicker resolve the issue.

**Comment by jbogard** [comment]
@michael-freidgeim-webjet Can you open a new issue so I can track that separately? Thanks!
