### ISSUE TITLE
Adding AutoMapper Breaks Scaffolding

### ISSUE THREAD

**Issue by InvestNextDoor** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#3]
When I add AutoMapper and the AutoMapper DI for ASP.NET Core. It breaks the MVC scaffolding.
This is a newly created project so no major customizations... 

Finding the generator 'controller'...
Running the generator 'controller'...
Attempting to compile the application in memory with the modified DbContext
Attempting to figure out the EntityFramework metadata for the model and DbContext: Donor
Exception has been thrown by the target of an invocation. StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.Internal.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection exportServices)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.EntityFrameworkServices.TryCreateContextUsingAppCode(Type dbContextType, ModelType startupType)
Object reference not set to an instance of an object. StackTrace:
There was an error creating the DbContext instance to get the model. No parameterless constructor defined for this object.   at AutoMapper.ServiceCollectionExtensions.AddAutoMapper(IServiceCollection services, Action`1 additionalInitAction, DependencyContext dependencyContext)

No parameterless constructor defined for this object.   at Tikanagan.Web.Startup.ConfigureServices(IServiceCollection services)

   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:09.88

**Comment by jbogard** [comment]
Scaffolding?

**Comment by InvestNextDoor** [comment]
When using the Visual Studio code generation for an entity to add the Controller and Views

**Comment by jbogard** [comment]
I'm sorry, I've still never used this. Do you have a link on how to do this?

**Comment by jbogard** [comment]
:man_shrugging:
