### ISSUE TITLE
AfterMap with IMappingAction and IHttpContextAccessor throwing error

### ISSUE THREAD

**Issue by adamkjonesmesh** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#70]
I have followed the example found [here](https://github.com/AutoMapper/AutoMapper/blob/master/docs/Before-and-after-map-actions.md).  I have a class as follows:

```
public class FileServiceRequestMappingAction : IMappingAction<FileServiceRequest, FileSearchRequest>
    {
        private readonly IHttpContextAccessor _httpContextAccessor;

        public FileServiceRequestMappingAction(IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
        }

        public void Process(FileServiceRequest source, FileSearchRequest destination)
        {
            try
            {
                destination.Filter = "somevalue";

                var storageType = "somestoragetype";

                if (_httpContextAccessor.HttpContext.Request.Path.Value.ToLower().Contains("/patha/"))
                {
                    storageType = "someothertypeofstorage";
                }

                if (!string.IsNullOrWhiteSpace(destination.Filter))
                {
                    destination.Filter += $" and storageType eq {storageType}";
                }
                else
                {
                    destination.Filter += $"storageType eq {storageType}";
                }
            }
            catch (Exception ex)
            {
                throw new TranslationException($"Error in filter. {ex.Message}");
            }
        }
    }
```

In my startup I have:

```
services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
services.AddAutoMapper(typeof(FileServiceRequestMappingAction).Assembly);
```

When I fire up the app and execute my api query where the map is called, I get the following error:
```
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at AutoMapper.Configuration.MappingExpression`2.<>c__60`1.<AfterMap>g__AfterFunction|60_0(TSource src, TDestination dest, ResolutionContext ctxt) in C:\projects\automapper\src\AutoMapper\Configuration\MappingExpression.cs:line 450
   at lambda_method(Closure , FileServiceRequest , FileSearchRequest , ResolutionContext )
   at lambda_method(Closure , Object , Object , ResolutionContext )
   at AutoMapper.Mapper.AutoMapper.IMapper.Map[TDestination](Object source) in C:\projects\automapper\src\AutoMapper\Mapper.cs:line 207
```

The error message is:
```
No parameterless constructor defined for this object.
```

I am sure I'm doing something wrong.  Note that in the startup.cs file, I have tried services.AddAutoMapper(typeof(Startup).Assembly); as well.  It doesn't work either.

Any thoughts, anyone?

Thanks.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by adamkjonesmesh** [comment]
Ok, posted to StackOverflow [here](https://stackoverflow.com/questions/52387800/aftermap-with-imappingaction-and-ihttpcontextaccessor-throwing-error).

**Comment by adamkjonesmesh** [comment]
just FYI: I fixed this by switching to using a Profile instead of a direct map (direct map being the old way of creating maps).
