### ISSUE TITLE
Notimplemented Exception in runtime

### ISSUE THREAD

**Issue by kooshanabedian** [AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#72]
Hi,
using this line of code

```
services.AddAutoMapper(mapperConfig => mapperConfig.AddProfiles(GetType().Assembly));
```

I get this exception upon running the application on dotnetcore 2.2 preview 2

```
Unhandled Exception: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'get_IsConnecting' in type 'Serilog.Sinks.Redis.List.NoConnectionMultiplexer' from assembly 'Serilog.Sinks.Redis.List, Version=1.3.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at AutoMapper.ServiceCollectionExtensions.<>c.<AddAutoMapperClasses>b__10_2(Assembly a) in C:\projects\automapper-extensions-microsoft-dependencyinjectio\src\AutoMapper.Extensions.Microsoft.DependencyInjection\ServiceCollectionExtensions.cs:line 71
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at AutoMapper.ServiceCollectionExtensions.AddAutoMapperClasses(IServiceCollection services, Action`1 additionalInitAction, IEnumerable`1 assembliesToScan) in C:\projects\automapper-extensions-microsoft-dependencyinjectio\src\AutoMapper.Extensions.Microsoft.DependencyInjection\ServiceCollectionExtensions.cs:line 69
   at AutoMapper.ServiceCollectionExtensions.AddAutoMapper(IServiceCollection services, Action`1 additionalInitAction, Assembly[] assemblies) in C:\projects\automapper-extensions-microsoft-dependencyinjectio\src\AutoMapper.Extensions.Microsoft.DependencyInjection\ServiceCollectionExtensions.cs:line 36
   at AutoMapper.ServiceCollectionExtensions.AddAutoMapper(IServiceCollection services, Action`1 additionalInitAction) in C:\projects\automapper-extensions-microsoft-dependencyinjectio\src\AutoMapper.Extensions.Microsoft.DependencyInjection\ServiceCollectionExtensions.cs:line 27
```

**Comment by lbargaoanu** [comment]
@jbogard I'm not saying it's necessarily a good idea, but it's possible to catch that exception and work with the types that can be loaded.

**Comment by kooshan** [comment]
Correct.
Using

```
var config = new AutoMapper.MapperConfiguration(cfg =>
            {
                cfg.AddProfiles
                (
                    typeof(ViewModelMappings1),
                    typeof(ViewModelMappings2),
                    typeof(ViewModelMappings3)
                );
            });
            var mapper = config.CreateMapper();
            services.AddSingleton(mapper);
```
solved the problem.
